name: testing-with-quickcheck
version: 0.0.1.0
ghc-options: -Wall -Werror -Wno-unused-matches -Wincomplete-uni-patterns -Wincomplete-record-updates -Wmissing-import-lists

dependencies: 
  - base

library:
  source-dirs: lib
  exposed-modules:
    - Lib

executables:
  testing-with-quickcheck:
    source-dirs: app
    main: Main.hs 
    dependencies:
      - testing-with-quickcheck

tests:
  qc-test:
    source-dirs: test
    main: QCMain.hs
    dependencies:
      - QuickCheck
      - testing-with-quickcheck
